#
# Input:
# * MYPROJECT
# * VERSION, VERSION(MAJOR|MINOR|PATCH)
# * MYDESCRIPTION
# * MYEXECUTABLES (optional), MYSTRIP (optional) (LINUX)

# Useful Variables
STRING(TOLOWER "${MYPROJECT}" MYPROJECT_LOWER)
SET(MYPROJECT_PACKAGE_FILE_NAME
"${MYPROJECT_LOWER}-${VERSION}-${OS}-${MYPROJECT_HOST_STR}")
SET(MYPROJECT_SRC_PACKAGE_FILE_NAME "${MYPROJECT_LOWER}-${VERSION}")

IF(DEFINED(MYEXECUTABLES))
ELSE()
IF(WIN32)
SET(MYEXECUTABLES "${MYPROJECT_LOWER}.exe")
ELSE(WIN32)
SET(MYEXECUTABLES "${MYPROJECT_LOWER}")
ENDIF(WIN32)
ENDIF()

IF(DEFINED(MYSTRIP))
ELSE()
IF(WIN32)
	SET(MYSTRIP "")
ELSE(WIN32)
	SET(MYSTRIP "bin/${MYPROJECT_LOWER}")
ENDIF(WIN32)
ENDIF()

# Basic Description
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "${MYPROJECT} - ${DESCRIPTION}")
SET(CPACK_PACKAGE_FILE_NAME ${MYPROJECT_PACKAGE_FILE_NAME})
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "${MYPROJECT_SRC_PACKAGE_FILE_NAME}")
#SET(CPACK_PACKAGE_NAME "${MYPROJECT_PACKAGE_FILE_NAME}") # just ${MYPROJECT} ?
SET(CPACK_PACKAGE_VENDOR "${MYPROJECT} Developers")
SET(CPACK_PACKAGE_VERSION ${VERSION})
SET(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
SET(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
SET(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE.txt")
SET(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.txt")
# SET(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_BINARY_DIR}/WELCOME.txt")
SET(CPACK_SOURCE_GENERATOR "TBZ2")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "${MYPROJECT_SRC_PACKAGE_FILE_NAME}")

# ...
SET(CPACK_PACKAGE_EXECUTABLES "${MYEXECUTABLES}")
SET(CPACK_STRIP_FILES "${MYSTRIP}")

# Include CPack
INCLUDE(CPack)

